modificados:     dev-fwiptables 	modificados:     fwiptables-v4.10-Alicante

diff --git a/dev-fwiptables b/dev-fwiptables
--- a/dev-fwiptables
+++ b/dev-fwiptables
@@ -424,7 +424,7 @@ net_ipv6_client="::/0" ; net_ipv6_server="::/0" ;
 ####     #### spanish: variable para comprobar si fwiptables esta instalado
 ####
 ####
-if [ "$1" != "install" ] && [ "$1" != "upgrade" ] ; then
+if [ "$1" != "install" ] && [ "$1" != "upgrade" ] && [ "$1" != "dev-upgrade" ]; then
 cmp -s $0 $directory_binary/$cmd_fwiptables || fwiptables_installed="no" 
 fi
 ####
@@ -618,164 +618,7 @@ if [ "$command_mpg123" = "$NULL" ]; then $nada ; else favorite_radio_command="$c
 ####
 ####
 #### :rutina-final-favorite-music-command:
-##########   english: uninstall:      fwiptables uninstall      ##########
-##########   spanish: desinstalador:  fwiptables desistalador   ##########
-#### :rutina-inicial-uninstall:
-####
-####
-if [ "$first_option" = "uninstall" ] ; then $zero_option intro
-echo "$header_ok [ $first_option ] [ $cmd_fwiptables uninstaller ] [ uninstall.md ] || ||"
-echo "$text_md [ info ] [ $name_fwiptables uninstalling.. ]"
-if  [ -f $directory_binary/$cmd_fwiptables ]; then
-rm $directory_binary/$cmd_fwiptables &> /dev/null
-rm $directory_binary/$name_fwiptables-cli-menu &> /dev/null
-rm $directory_binary/$name_fwiptables-gui-menu &> /dev/null
-rm $directory_binary/$name_fwiptables-gui-shell &> /dev/null
-echo "$text_md [ info ] [ deleted binaries ]"
-echo "$text_md [  ok  ] [ $name_fwiptables uninstalled ]" ;
-else echo "$text_md [ info ] [ $cmd_fwiptables is not installed ]"; fi
-exit; fi
-####
-####
-#### :rutina-final-uninstall:
-##########       english: install:    fwiptables install          ##########
-##########       spanish: instalador: fwiptables instalador       ##########
-#### :rutina-inicial-install:
-####
-####
-if [ "$first_option" = "install" ] ; then echo $give_cover
-echo "$header_ok [ $first_option ] [ $name_fwiptables $fversion installer ] [ install.md ] || ||"
-####
-####
-####  english: copy the file to temporal folder and install
-####  spanish: copia el archivo a carpeta temporal y instala
-#### 
-#### 
-echo "$text_md [ info ] [ $name_fwiptables installing.. ]"
-cp "$zero_option" "$directory_temporal/fwiptables-tmp.sh" &> /dev/null
-cp "$directory_temporal/fwiptables-tmp.sh" "$directory_binary/$cmd_fwiptables" &> /dev/null 
-chmod 555 "$directory_binary/$cmd_fwiptables" &> /dev/null 
-####
-####
-####  english: generate fwiptables default
-####  spanish: genera fwiptables default
-####
-####
-echo "$(head -310 $0 | $command_grep -B 2 fwiptables-file-default)" &> "$directory_default/$name_fwiptables-default"
-$cmd_fwiptables regen-config &> /dev/null
-####
-####
-####  english: generate fwiptables-gui-menu fwiptables-gui-shell and fwiptables-cli-menu in /usr/bin
-####  spanish: genera fwiptables-gui-menu fwiptables-gui-shell y fwiptables-cli-menu en /usr/bin
-####
-####
-echo "#!/bin/bash" &> $directory_binary/$name_fwiptables-cli-menu
-echo "sudo $cmd_fwiptables cli-menu" &>> $directory_binary/$name_fwiptables-cli-menu
-chmod 555 $directory_binary/$name_fwiptables-cli-menu &> /dev/null
-####
-####
-echo "#!/bin/bash" &> $directory_binary/$name_fwiptables-gui-menu
-echo "$command_xhost +SI:localuser:root" &>> $directory_binary/$name_fwiptables-gui-menu
-echo "sudo $cmd_fwiptables gui-menu" &>> $directory_binary/$name_fwiptables-gui-menu
-chmod 555 $directory_binary/$name_fwiptables-gui-menu &> /dev/null
-####
-####
-echo "#!/bin/bash" &> $directory_binary/$name_fwiptables-gui-shell
-echo "$command_xhost +SI:localuser:root" &>> $directory_binary/$name_fwiptables-gui-shell
-echo "sudo $cmd_fwiptables gui-shell" &>> $directory_binary/$name_fwiptables-gui-shell
-chmod 555 $directory_binary/$name_fwiptables-gui-shell &> /dev/null
-####
-####
-####   english: Show final status from installer
-####   spanish: Muestra el estatus final desde el instalador
-####
-####
-echo "$text_md [ info ] [ Config dir:        ] [ $directory_data ]"
-echo "$text_md [ info ] [ Tmp dir:           ] [ $directory_tmp  ]"
-echo "$text_md [ info ] [ Command shell:     ] [ $directory_binary/$cmd_fwiptables ]"
-echo "$text_md [ info ] [ command cli-menu:  ] [ $directory_binary/$name_fwiptables-cli-menu  ]"
-echo "$text_md [ info ] [ command gui-menu:  ] [ $directory_binary/$name_fwiptables-gui-menu  ]"
-echo "$text_md [ info ] [ command gui-shell: ] [ $directory_binary/$name_fwiptables-gui-shell ]"
-echo "$text_md [ info ] [ Grant privileges to user: ] [ $cmd_fwiptables sudofw-adduser user ]"
-echo "$text_md [  ok  ] [ Now. You are ready to run $cmd_fwiptables ]"
-exit; fi
-####
-####
-#### :rutina-final-install:
-##########       english: upgrade: upgrade in the file /usr/bin/fwiptables        ##########
-##########       spanish: upgrade: actualiza en el archivo /usr/bin/fwiptables    ##########
-#### :rutina-inicial-upgrade:
-####
-####
-if [ "$first_option" = "upgrade" ]; then echo $give_cover
-echo "$header_ok [ $first_option ] [ upgrade latest version from web ] [ upgrade.md ] || ||"
-echo "$text_md [ info ] [ upgrade $cmd_fwiptables at latest version from sourceforge.net web ]"
-####  echo "$text_md [ info ] [ upgrade $cmd_fwiptables in $directory_binary ]"
-case "$favorite_text_browser" in
-"$NULL")echo "$text_md $tab [ notice ] [ Install a text web browser for upgrade fwiptables ]"; exit ;; esac
-echo "$text_md [ info ] [ Upgrade The $cmd_fwiptables in file $directory_binary/$cmd_fwiptables with $favorite_text_browser command ]"
-echo "$text_md [ info ] [ Downloading $cmd_fwiptables with the command $favorite_text_browser browser ]"
-####
-####
-####  English: download fwiptables
-####  Spanish: descarga fwiptables
-####
-####
-echo "$text_md [ downloading ] [ $fweb_latest ]"
-echo "$text_md [ info ] [ Waiting several seconds .. ]"
-$favorite_text_browser -source "$fweb_latest" &> "$directory_temporal/$name_fwiptables" || echo "[ fail ] [ disconnected ]"
-chmod ugo+rwx "$directory_temporal/$name_fwiptables" &> /dev/null
-####
-####
-#### English: launch install
-#### Spanish: lanza instalacion
-####
-####
-if [ -f "$directory_temporal/$name_fwiptables" ] ;
-then "$directory_temporal/$name_fwiptables" install ; 
-else echo "$text_md [ fail ] [ Install fail ]"; fi
-exit ; fi
-####
-####
-#### :rutina-final-upgrade:
-##########    english: dev-upgrade: upgrade in the file /usr/bin/fwiptables       ##########
-##########    spanish: dev-upgrade: actualiza en el archivo /usr/bin/fwiptables   ##########
-#### :rutina-inicial-dev-upgrade:
-####
-####
-if [ "$first_option" = "dev-upgrade" ]; then echo $give_cover
-echo "$header_ok [ $first_option ] [ upgrade development version from web ] [ upgrade.md ] || ||"
-echo "$text_md [ info ] [ upgrade $cmd_fwiptables at development version from sourceforge.net git ]"
-####  echo "$text_md [ info ] [ upgrade $cmd_fwiptables in $directory_binary ]"
-case "$favorite_text_browser" in
-"$NULL")echo "$text_md $tab [ notice ] [ Install a text web browser for upgrade fwiptables ]"; exit ;; esac
-echo "$text_md [ info ] [ Upgrade The $cmd_fwiptables in file $directory_binary/$cmd_fwiptables with $favorite_text_browser command ]"
-echo "$text_md [ info ] [ Downloading $cmd_fwiptables with the command $favorite_text_browser browser ]"
-####
-####
-####  English: download fwiptables
-####  Spanish: descarga fwiptables
-####
-####
-echo "$text_md [ downloading ] [ $fweb_development ]"
-echo "$text_md [ info ] [ Waiting several seconds .. ]"
-$favorite_text_browser -source $fweb_development &> "$directory_temporal/$name_fwiptables-installer" || echo "[ fail ] [ disconnected ]"
-chmod ugo+rx $directory_temporal/$name_fwiptables-installer &> /dev/null
-####
-####
-#### English: launch install
-#### Spanish: lanza instalacion
-####
-####
-if [ -s "$directory_temporal/$name_fwiptables-installer" ] ;
-then $directory_temporal/$name_fwiptables-installer install ; 
-else echo "$text_md [ fail ] [ Install fail ]"; fi
-####
-####
-exit ; fi
-####
-####
-#### :rutina-final-dev-upgrade:
+
 ##########    english: Notice Installer with intro      ##########
 ##########    spanish: noticia de Instalador con intro  ##########
 #### :rutina-inicial-notice:
@@ -914,7 +757,6 @@ cat $temporal_textfinal ; exit ;;
 ####
 ####
 esac ; $cmd_fwiptables "$second_option" "$third_option" "$quad_option"
-#### first_option="$second_option"; second_option="$third_option"; third_option="$quad_option" 
 ####
 ####
 exit; fi
@@ -926,8 +768,6 @@ exit; fi
 if [ "$first_option" = "-cli" ]
 then echo $head_waiting_cli
 case "$second_option" in
-## "ls6"|"list6") second_option="list-filter4" ; exit ;; 
-## "ls"|"ls4"|"list") second_option="list-filter6" ; exit ;; 
 wizard-*) echo $message_without_cli ; $cmd_fwiptables $second_option $third_option ;  exit ;;
 "nueva-mini-config")  $cmd_fwiptables $second_option $third_option ;  exit ;;
 "nueva-completa-config") $cmd_fwiptables $second_option $third_option ;  exit ;;
@@ -1170,6 +1010,164 @@ if [ "$allow_autolog" != "no" ]; then echo $head_autolog >> "$output_autolog" ; 
 ####
 ####
 #### :rutina-final-allow-autolog:
+##########   english: uninstall:      fwiptables uninstall      ##########
+##########   spanish: desinstalador:  fwiptables desistalador   ##########
+#### :rutina-inicial-uninstall:
+####
+####
+if [ "$first_option" = "uninstall" ] ; then $zero_option intro
+echo "$header_ok [ $first_option ] [ $cmd_fwiptables uninstaller ] [ uninstall.md ] || ||"
+echo "$text_md [ info ] [ $name_fwiptables uninstalling.. ]"
+if  [ -f $directory_binary/$cmd_fwiptables ]; then
+rm $directory_binary/$cmd_fwiptables &> /dev/null
+rm $directory_binary/$name_fwiptables-cli-menu &> /dev/null
+rm $directory_binary/$name_fwiptables-gui-menu &> /dev/null
+rm $directory_binary/$name_fwiptables-gui-shell &> /dev/null
+echo "$text_md [ info ] [ deleted binaries ]"
+echo "$text_md [  ok  ] [ $name_fwiptables uninstalled ]" ;
+else echo "$text_md [ info ] [ $cmd_fwiptables is not installed ]"; fi
+exit; fi
+####
+####
+#### :rutina-final-uninstall:
+##########       english: install:    fwiptables install          ##########
+##########       spanish: instalador: fwiptables instalador       ##########
+#### :rutina-inicial-install:
+####
+####
+if [ "$first_option" = "install" ] ; then echo $give_cover
+echo "$header_ok [ $first_option ] [ $name_fwiptables $fversion installer ] [ install.md ] || ||"
+####
+####
+####  english: copy the file to temporal folder and install
+####  spanish: copia el archivo a carpeta temporal y instala
+#### 
+#### 
+echo "$text_md [ info ] [ $name_fwiptables installing.. ]"
+cp "$zero_option" "$directory_temporal/fwiptables-tmp.sh" &> /dev/null
+cp "$directory_temporal/fwiptables-tmp.sh" "$directory_binary/$cmd_fwiptables" &> /dev/null 
+chmod 555 "$directory_binary/$cmd_fwiptables" &> /dev/null 
+####
+####
+####  english: generate fwiptables default
+####  spanish: genera fwiptables default
+####
+####
+echo "$(head -310 $0 | $command_grep -B 2 fwiptables-file-default)" &> "$directory_default/$name_fwiptables-default"
+$cmd_fwiptables regen-config &> /dev/null
+####
+####
+####  english: generate fwiptables-gui-menu fwiptables-gui-shell and fwiptables-cli-menu in /usr/bin
+####  spanish: genera fwiptables-gui-menu fwiptables-gui-shell y fwiptables-cli-menu en /usr/bin
+####
+####
+echo "#!/bin/bash" &> $directory_binary/$name_fwiptables-cli-menu
+echo "sudo $cmd_fwiptables cli-menu" &>> $directory_binary/$name_fwiptables-cli-menu
+chmod 555 $directory_binary/$name_fwiptables-cli-menu &> /dev/null
+####
+####
+echo "#!/bin/bash" &> $directory_binary/$name_fwiptables-gui-menu
+echo "$command_xhost +SI:localuser:root" &>> $directory_binary/$name_fwiptables-gui-menu
+echo "sudo $cmd_fwiptables gui-menu" &>> $directory_binary/$name_fwiptables-gui-menu
+chmod 555 $directory_binary/$name_fwiptables-gui-menu &> /dev/null
+####
+####
+echo "#!/bin/bash" &> $directory_binary/$name_fwiptables-gui-shell
+echo "$command_xhost +SI:localuser:root" &>> $directory_binary/$name_fwiptables-gui-shell
+echo "sudo $cmd_fwiptables gui-shell" &>> $directory_binary/$name_fwiptables-gui-shell
+chmod 555 $directory_binary/$name_fwiptables-gui-shell &> /dev/null
+####
+####
+####   english: Show final status from installer
+####   spanish: Muestra el estatus final desde el instalador
+####
+####
+echo "$text_md [ info ] [ Config dir:        ] [ $directory_data ]"
+echo "$text_md [ info ] [ Tmp dir:           ] [ $directory_tmp  ]"
+echo "$text_md [ info ] [ Command shell:     ] [ $directory_binary/$cmd_fwiptables ]"
+echo "$text_md [ info ] [ command cli-menu:  ] [ $directory_binary/$name_fwiptables-cli-menu  ]"
+echo "$text_md [ info ] [ command gui-menu:  ] [ $directory_binary/$name_fwiptables-gui-menu  ]"
+echo "$text_md [ info ] [ command gui-shell: ] [ $directory_binary/$name_fwiptables-gui-shell ]"
+echo "$text_md [ info ] [ Grant privileges to user: ] [ $cmd_fwiptables sudofw-adduser user ]"
+echo "$text_md [  ok  ] [ Now. You are ready to run $cmd_fwiptables ]"
+exit; fi
+####
+####
+#### :rutina-final-install:
+##########       english: upgrade: upgrade in the file /usr/bin/fwiptables        ##########
+##########       spanish: upgrade: actualiza en el archivo /usr/bin/fwiptables    ##########
+#### :rutina-inicial-upgrade:
+####
+####
+if [ "$first_option" = "upgrade" ]; then echo $give_cover
+echo "$header_ok [ $first_option ] [ upgrade latest version from web ] [ upgrade.md ] || ||"
+echo "$text_md [ info ] [ upgrade $cmd_fwiptables at latest version from sourceforge.net web ]"
+####  echo "$text_md [ info ] [ upgrade $cmd_fwiptables in $directory_binary ]"
+case "$favorite_text_browser" in
+"$NULL")echo "$text_md $tab [ notice ] [ Install a text web browser for upgrade fwiptables ]"; exit ;; esac
+echo "$text_md [ info ] [ Upgrade The $cmd_fwiptables in file $directory_binary/$cmd_fwiptables with $favorite_text_browser command ]"
+echo "$text_md [ info ] [ Downloading $cmd_fwiptables with the command $favorite_text_browser browser ]"
+####
+####
+####  English: download fwiptables
+####  Spanish: descarga fwiptables
+####
+####
+echo "$text_md [ downloading ] [ $fweb_latest ]"
+echo "$text_md [ info ] [ Waiting several seconds .. ]"
+$favorite_text_browser -source "$fweb_latest" &> "$directory_temporal/$name_fwiptables" || echo "[ fail ] [ disconnected ]"
+chmod ugo+rwx "$directory_temporal/$name_fwiptables" &> /dev/null
+####
+####
+#### English: launch install
+#### Spanish: lanza instalacion
+####
+####
+if [ -f "$directory_temporal/$name_fwiptables" ] ;
+then "$directory_temporal/$name_fwiptables" install ; 
+else echo "$text_md [ fail ] [ Install fail ]"; fi
+exit ; fi
+####
+####
+#### :rutina-final-upgrade:
+##########    english: dev-upgrade: upgrade in the file /usr/bin/fwiptables       ##########
+##########    spanish: dev-upgrade: actualiza en el archivo /usr/bin/fwiptables   ##########
+#### :rutina-inicial-dev-upgrade:
+####
+####
+if [ "$first_option" = "dev-upgrade" ]; then echo $give_cover
+echo "$header_ok [ $first_option ] [ upgrade development version from web ] [ upgrade.md ] || ||"
+echo "$text_md [ info ] [ upgrade $cmd_fwiptables at development version from sourceforge.net git ]"
+####  echo "$text_md [ info ] [ upgrade $cmd_fwiptables in $directory_binary ]"
+case "$favorite_text_browser" in
+"$NULL")echo "$text_md $tab [ notice ] [ Install a text web browser for upgrade fwiptables ]"; exit ;; esac
+echo "$text_md [ info ] [ Upgrade The $cmd_fwiptables in file $directory_binary/$cmd_fwiptables with $favorite_text_browser command ]"
+echo "$text_md [ info ] [ Downloading $cmd_fwiptables with the command $favorite_text_browser browser ]"
+####
+####
+####  English: download fwiptables
+####  Spanish: descarga fwiptables
+####
+####
+echo "$text_md [ downloading ] [ $fweb_development ]"
+echo "$text_md [ info ] [ Waiting several seconds .. ]"
+$favorite_text_browser -source $fweb_development &> "$directory_temporal/$name_fwiptables-installer" || echo "[ fail ] [ disconnected ]"
+chmod ugo+rx $directory_temporal/$name_fwiptables-installer &> /dev/null
+####
+####
+#### English: launch install
+#### Spanish: lanza instalacion
+####
+####
+if [ -s "$directory_temporal/$name_fwiptables-installer" ] ;
+then $directory_temporal/$name_fwiptables-installer install ; 
+else echo "$text_md [ fail ] [ Install fail ]"; fi
+####
+####
+exit ; fi
+####
+####
+#### :rutina-final-dev-upgrade:
 ##########   english: regen-config: regen-config template wizard files       ##########
 ##########   spanish: regen-config: regen-configera template wizard archivos ##########
 #### :rutina-inicial-regen-config:
