modificados:     dev-fwiptables 	modificados:     fwiptables-complete-v6.08

diff --git a/dev-fwiptables b/dev-fwiptables
--- a/dev-fwiptables
+++ b/dev-fwiptables
@@ -626,8 +626,8 @@ fi
 ####
 ####
 if [ "$favorite_graphicall_dialog" == "$NULL" ]; then
+# if [ "$command_yad"     != "$NULL" ] ; then  favorite_graphicall_dialog="$command_yad"      ; fi
 if [ "$command_zenity"  != "$NULL" ] ; then  favorite_graphicall_dialog="$command_zenity"   ; fi
-if [ "$command_yad"     != "$NULL" ] ; then  favorite_graphicall_dialog="$command_yad"      ; fi
 fi
 ####
 ####
@@ -4676,7 +4676,7 @@ exit; fi
 ####
 ####
 if   [ "$first_option" = "gui-menu" ] ; then echo $head_waiting_gui
-case "$favorite_graphicall_dialog" in "$NULL") echo "$duo_md [ fail ] [ Install zenity to work ]"; exit ;; esac
+case "$favorite_graphicall_dialog" in "$NULL") echo "$duo_md [ fail ] [ Install or yad or zenity to work ]"; exit ;; esac
 selection=$(zenity $graphic_dimension  \
  --list "01 Firewall Control" "02 Firewall List With Conceptual" "02 Firewall List With Numeral" \
 "03 Firewall Custom" "04 Firewall Launch" "05 Options State" "06 Tool sockets" \
@@ -4927,7 +4927,7 @@ exit; fi
 ####
 ####
 if   [ "$first_option" = "gui-menu-firewall-custom" ] ; then $nada ;
-selection=$(zenity $graphic_dimension \
+selection=$($favorite_graphicall_dialog $graphic_dimension \
 --list "Gui Principal Menu" "Gui Help Menu" "Gui Info Menu" "new-full-config" "nueva-completa-config" "new-mini-config" "nueva-mini-config" \
 "names-config" "show-config" "modify-config" "del-config" "regen-config" "examples-config" \
 --column="Option list $cmd_binary" --text="Select one option" --title="[ Firewall custom ] [ $cmd_binary ]" )
@@ -4980,29 +4980,27 @@ exit; fi
 #### :rutina-inicial-gui-menu-options-state:
 ####
 ####
-if   [ "$first_option" = "gui-menu-options-state" ] ; then $nada ;
-"$($favorite_graphicall_dialog  $graphic_dimension \
---list "Gui Principal Menu" "Gui Help Menu" "Gui Info Menu" "preferences-read" "preferences-modify" "preferences-regen" \
-ip4 ip6 version examples depends install upgrade \
---column="Option list" --text="Select one option" --title="[ Firewall Rules ]")"
+if   [ "$first_option" = "gui-menu-options-state" ] ; then 
+selection_list="$($favorite_graphicall_dialog $graphic_dimension --column="Option list" --text="Select one option" --title="[ Firewall Rules ]" \
+--list Gui-Principal-Menu Gui-Help-Menu Gui-Info-Menu preferences-read preferences-modify preferences-regen ip4 ip6 version examples depends install upgrade)"
 #### 
 ####
-selection1="$?"
-case $selection in
-### 1)$favorite_graphicall_dialog  --info $graphic_dimension --text="$cmd_binary good bye"; exit ;;
-"Gui Principal Menu")$cmd_binary gui-menu ;;
-"Gui Help Menu")$cmd_binary -gui help status-state ;;
-"Gui Info Menu")$cmd_binary -gui info status-state ;;
-"preferences-read")$cmd_binary -gui preferences-read ;;
-"preferences-modify")$cmd_binary -gui preferences-modify ;;
-"preferences-regen")$cmd_binary -gui preferences-regen ;;
-"ip4|")$cmd_binary -gui ip4 ;;
-"ip6")$cmd_binary -gui ip6 ;;
-"version")$cmd_binary -gui version ;;
-"examples")$cmd_binary -gui examples ;;
-"depends")$cmd_binary -gui depends ;;
-"install")$cmd_binary -gui install ;;
-"upgrade")$cmd_binary -gui upgrade ;;
+# selection_uno="$?"
+case $selection_list in
+1)$favorite_graphicall_dialog  --info $graphic_dimension --text="$cmd_binary good bye"; exit ;;
+Gui-Principal-Menu)$cmd_binary gui-menu ;;
+Gui-Help-Menu)$cmd_binary -gui help status-state ;;
+Gui-Info-Menu)$cmd_binary -gui info status-state ;;
+preferences-read)$cmd_binary -gui preferences-read ;;
+preferences-modify)$cmd_binary -gui preferences-modify ;;
+preferences-regen)$cmd_binary -gui preferences-regen ;;
+ip4)$cmd_binary -gui ip4 ;;
+ip6)$cmd_binary -gui ip6 ;;
+version)$cmd_binary -gui version ;;
+examples)$cmd_binary -gui examples ;;
+depends)$cmd_binary -gui depends ;;
+install)$cmd_binary -gui install ;;
+upgrade)$cmd_binary -gui upgrade ;;
 esac
 ####
 ####
